### ISSUE TITLE
Drop reqwest dependency

### ISSUE THREAD

**Issue by termoshtt** [rust-math/fftw#89]
From #83 

- For Linux and macOS, #88 make possible to drop download phase
- For Windows, however, downloading is still needed to get compiled binary. We have some choice:
  - Also compile with GNU toolchain, and drop msvc support
  - Use reqwest or more light downloader, e.g. [curl crate](https://github.com/alexcrichton/curl-rust) which is used in `intel-mkl-src` if `download` feature is enabled,  only for Windows
  - or combine them (build for gnu, and download for msvc)

**Comment by LingMan** [comment]
Actually the Windows download path doesn't even use reqwest since it grabs the zip via FTP. I'll cook up a PR.

Much more problematic is that the precompiled dlls are only available up to fftw 3.3.5 (ftp://ftp.fftw.org/pub/fftw/ | [website](http://fftw.org/install/windows.html)). So now there is a divergence between Windows on 3.3.5 and the rest on 3.3.8.

Not to mention that the FTP isn't even encrypted so a MitM attack that inserts maliciously modified  dlls is somewhat easy.

**Comment by termoshtt** [comment]
> Actually the Windows download path doesn't even use reqwest

right, thanks PR!
